default_job = "run"
env.CARGO_TERM_COLOR = "always"

on_change_strategy = "kill_then_restart"

[jobs.run]
command = ["cargo", "make", "run"]
need_stdout = true
allow_warnings = true

[jobs.build]
command = ["cargo", "build"]
need_stdout = true
allow_warnings = true
