[package]
name = "qube-name"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ctor = "0.4.2"
qube-core = { version = "0.1.0", path = "../qube-core" }

[lints]
workspace = true
