name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      run: rustup update nightly && rustup default nightly && rustup component add clippy
    - name: Check
      run: RUSTFLAGS=-Dwarnings cargo check --all-targets --all-features
    - name: Clippy
      run: RUSTFLAGS=-Dwarnings cargo clippy --all-targets --all-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
